add gtk3 support to the packaging. Closes: #641140

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -27,9 +27,12 @@ override_dh_auto_install:
 		sed -i "/dependency_libs/ s/'.*'/''/" $$FILE; \
 	done
 	# move libraries based on gtk_binary_version
-	mkdir -p debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/gtk-2.0/`pkg-config --variable=gtk_binary_version gtk+-2.0`/
-	mv debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/gtk-2.0/immodules \
-		debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/gtk-2.0/`pkg-config --variable=gtk_binary_version gtk+-2.0`/
+	# continue on errors
+	for i in 2 3; do \
+	  mkdir -p debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/gtk-$$i.0/`pkg-config --variable=gtk_binary_version gtk+-$$i.0`/; \
+	  mv debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/gtk-$$i.0/immodules \
+		debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/gtk-$$i.0/`pkg-config --variable=gtk_binary_version gtk+-$$i.0`/ || true; \
+	done
 
 override_dh_installdocs:
 	dh_installdocs -X Makefile
@@ -45,7 +48,7 @@ override_dh_install:
 	dh_install
 	sed -i -e 's/@DEB_HOST_MULTIARCH@/$(DEB_HOST_MULTIARCH)/g' debian/scim/etc/X11/xinit/xinput.d/scim-immodule
 	LD_LIBRARY_PATH=debian/libscim8c2a/usr/lib/$(DEB_HOST_MULTIARCH):$(LD_LIBRARY_PATH) \
-		dh_gtkmodules -p scim-gtk2-immodule
+		dh_gtkmodules -p scim-gtk-immodule
 
 override_dh_makeshlibs:
 	dh_makeshlibs -p libscim8c2a -V "libscim8c2a (>= 1.4)"
